### PR TITLE
JSDoc fixes

### PR DESCRIPTION
**Pull request by Glinkis**
Fix incorrect jsdoc comments.

### CODE REVIEW

**Comment by jamesleesaunders** [comment]
Towards #22

**Comment by jamesleesaunders** [comment]
Just so you are aware - I may have someone adding the JSDoc node module and building the docs from code soon. They may also be looking to fix-up some doc blocks soon.

**Comment by Glinkis** [comment]
Okay, I don't think there will be any collision issues unless the person makes huge commits.

**Comment by Glinkis** [comment]
When building the documentation, it should be published to gh-pages, and not committed to the master branch.

**Pull request merged**
